import sys
from starts import *

if __name__=='__main__':
    app=QApplication(sys.argv)
    ex=myapp()
    ex.add_menu('파일','F')
    ex.add_act_ctrl('새로 만들기','N','N')
    ex.add_act_shift('새 창','W','N')
    ex.add_act_ctrl3('열기','O','O',ex.open_file)
    ex.add_act_ctrl('저장','S','S')
    ex.add_act_shift('다른 이름으로 저장','A','S')
    ex.add_sep()
    ex.add_act('페이지 설정','U')
    ex.add_act_ctrl('인쇄','P','P')
    ex.add_sep()
    ex.add_act2('끝내기','X',exit)
    
    ex.add_menu('편집','U')
    ex.add_act_ctrl('실행 취소','T','Z')
    ex.add_sep()
    ex.add_act_ctrl('잘라내기','X','X')
    ex.add_act_ctrl('복사','C','C')
    ex.add_act_ctrl('붙여넣기','P','V')
    ex.add_act_short('삭제','L','Del')
    ex.add_sep()
    ex.add_act_ctrl('Bing으로 검색','S','E')
    ex.add_act_ctrl('찾기','T','F')
    ex.add_act_short('다음 찾기','F','F3')
    ex.add_act_short('이전 찾기','N','Shift+F3')
    ex.add_act_ctrl('바꾸기','R','H')
    ex.add_act_ctrl('이동','G','G')
    ex.add_sep()
    ex.add_act_ctrl('모두 선택','A','A')
    ex.add_act_short('시간/날짜','D','F5')
    
    ex.add_menu('서식','O')
    ex.add_act('자동 줄바꿈','W')
    ex.add_act('글꼴','F')
    
    ex.add_menu('보기','V')
    ex.add_menu2('확대하기/ 축소하기','S')
    ex.add_act_ctrl2('확대','I','+')
    ex.add_act_ctrl2('축소','O','-')
    ex.add_act_ctrl2('확대하기/ 축소하기 기본값 복원','O',0)
    ex.add_act('상태 표시줄','S')

    ex.add_menu('도움말','H')
    ex.add_act('도움말 보기','H')
    ex.add_act('피드백 보내기','F')
    ex.add_sep()
    ex.add_act('메모장 정보','A')
    # ex.new_file()
    sys.exit(app.exec())